export const courses = [
   {
    title: "Competitive Exams",
    desc: "IIT JEE, NEET, ESE, GATE, AE/JE, Olympiad",
    items: [ { name: "IIT JAM", icon: "⚛️" },
      { name: "CSIR NET", icon: "🔬" },
      { name: "LAW", icon: "📜" },
      { name: "CUET", icon: "🎓" },
      { name: "UGC NET", icon: "🏛️" },
      { name: "GMAT", icon: "📘" },
      { name: "CUET", icon: "🎓" },
      { name: "UGC NET", icon: "🏛️" },
      { name: "GMAT", icon: "📘" },
      { name: "Design & Architecture", icon: "📐" },
      { name: "CUET PG", icon: "✅" },
      { name: "NEET PG", icon: "🧬" },
      { name: "Pharma", icon: "💊" },
    ],

  },
  {
    title: "Only IAS",
    desc: "UPSC, State PSC",
    items: [ { name: "IIT JAM", icon: "⚛️" },
      { name: "CSIR NET", icon: "🔬" },
      { name: "LAW", icon: "📜" },
      { name: "CUET", icon: "🎓" },
      { name: "UGC NET", icon: "🏛️" },
      { name: "GMAT", icon: "📘" },
     { name: "CUET", icon: "🎓" },
      { name: "UGC NET", icon: "🏛️" },
      { name: "GMAT", icon: "📘" },
      { name: "Design & Architecture", icon: "📐" },
      { name: "CUET PG", icon: "✅" },
      { name: "NEET PG", icon: "🧬" },
      { name: "Pharma", icon: "💊" },
    ], 
  },
  {
    title: "School Preparation",
    desc: "Foundation (Class 6-10), Commerce, Arts, CuriousJr, Science, International Boards",
    items: [ { name: "IIT JAM", icon: "⚛️" },
      { name: "CSIR NET", icon: "🔬" },
      { name: "LAW", icon: "📜" },
      { name: "CUET", icon: "🎓" },
      { name: "UGC NET", icon: "🏛️" },
      { name: "GMAT", icon: "📘" },
     { name: "CUET", icon: "🎓" },
      { name: "UGC NET", icon: "🏛️" },
      { name: "GMAT", icon: "📘" },
      { name: "Design & Architecture", icon: "📐" },
      { name: "CUET PG", icon: "✅" },
      { name: "NEET PG", icon: "🧬" },
      { name: "Pharma", icon: "💊" },
    ],
  },
  {
    title: "Govt Exam",
    desc: "SSC, Banking, Judiciary, Teaching, Railway, UP Exams, Defence, etc.",
    items: [ { name: "IIT JAM", icon: "⚛️" },
      { name: "CSIR NET", icon: "🔬" },
      { name: "LAW", icon: "📜" },
      { name: "CUET", icon: "🎓" },
      { name: "UGC NET", icon: "🏛️" },
      { name: "GMAT", icon: "📘" },
       { name: "CUET", icon: "🎓" },
      { name: "UGC NET", icon: "🏛️" },
      { name: "GMAT", icon: "📘" },
      { name: "Design & Architecture", icon: "📐" },
      { name: "CUET PG", icon: "✅" },
      { name: "NEET PG", icon: "🧬" },
      { name: "Pharma", icon: "💊" },
    ],
  },
  {
    title: "UG & PG Entrance Exams",
    desc: "MBA, IPMAT, IIT JAM, CSIR NET, LAW, CUET, UGC NET, GMAT, Design & Architecture, CUET PG, NEET PG, Pharma",
    items: [
      { name: "MBA", icon: "📚" },
      { name: "IPMAT", icon: "🎓" },
      { name: "IIT JAM", icon: "⚛️" },
      { name: "CSIR NET", icon: "🔬" },
      { name: "LAW", icon: "📜" },
      { name: "CUET", icon: "🎓" },
      { name: "UGC NET", icon: "🏛️" },
      { name: "GMAT", icon: "📘" },
      { name: "Design & Architecture", icon: "📐" },
      { name: "CUET PG", icon: "✅" },
      { name: "NEET PG", icon: "🧬" },
      { name: "Pharma", icon: "💊" },
    ],
  },
  {
    title: "Finance",
    desc: "CA, CS, ACCA",
    items: [ { name: "IIT JAM", icon: "⚛️" },
      { name: "CSIR NET", icon: "🔬" },
      { name: "LAW", icon: "📜" },
      { name: "CUET", icon: "🎓" },
      { name: "UGC NET", icon: "🏛️" },
      { name: "GMAT", icon: "📘" },],
  },
  {
    title: "Others",
    desc: "Online Degrees, Financial Certification, Private Banking",
    items: [ { name: "IIT JAM", icon: "⚛️" },
      { name: "CSIR NET", icon: "🔬" },
      { name: "LAW", icon: "📜" },
      { name: "CUET", icon: "🎓" },
      { name: "UGC NET", icon: "🏛️" },
      { name: "GMAT", icon: "📘" },
      { name: "CUET", icon: "🎓" },
      { name: "UGC NET", icon: "🏛️" },
      { name: "GMAT", icon: "📘" },
      { name: "Design & Architecture", icon: "📐" },
      { name: "CUET PG", icon: "✅" },
      { name: "NEET PG", icon: "🧬" },
      { name: "Pharma", icon: "💊" },
    ],
  },
 
];
